#!/usr/bin/env python3
"""Fetch transcript and metadata for one or more public YouTube videos."""

from __future__ import annotations

import json
import re
import sys
from dataclasses import dataclass, asdict
from html import unescape
from typing import Any
import urllib.request
from urllib.parse import parse_qs, urlparse


@dataclass
class TranscriptResult:
    input_url: str
    canonical_url: str | None = None
    video_id: str | None = None
    title: str | None = None
    publish_date: str | None = None
    duration_seconds: int | None = None
    duration_human: str | None = None
    transcript_language: str | None = None
    transcript_language_code: str | None = None
    transcript_source: str | None = None
    retrieval_method: str | None = None
    transcript: str | None = None
    attempted_methods: list[str] | None = None
    failure_reason: str | None = None


def parse_video_id(url: str) -> tuple[str | None, str | None]:
    try:
        parsed = urlparse(url)
    except Exception:
        return None, None

    hostname = (parsed.hostname or '').lower()
    if hostname.endswith('youtu.be'):
        video_id = parsed.path.strip('/').split('/')[0]
    elif 'youtube.com' in hostname or 'youtube-nocookie.com' in hostname:
        if parsed.path == '/watch':
            video_id = parse_qs(parsed.query).get('v', [None])[0]
        elif parsed.path.startswith('/shorts/') or parsed.path.startswith('/embed/'):
            video_id = parsed.path.strip('/').split('/')[1]
        else:
            video_id = None
    else:
        video_id = None

    if not video_id or not re.fullmatch(r'[A-Za-z0-9_-]{6,}', video_id):
        return None, None

    return video_id, f'https://www.youtube.com/watch?v={video_id}'


def format_duration(total_seconds: int | None) -> str | None:
    if total_seconds is None:
        return None
    hours, remainder = divmod(int(total_seconds), 3600)
    minutes, seconds = divmod(remainder, 60)
    if hours:
        return f'{hours}:{minutes:02d}:{seconds:02d}'
    return f'{minutes}:{seconds:02d}'


def normalize_text(text: str) -> str:
    text = unescape(text)
    text = text.replace('\xa0', ' ')
    text = re.sub(r'\s+', ' ', text)
    text = re.sub(r' ?\n ?', '\n', text)
    return text.strip()


def transcript_line_text(item: Any) -> str:
    """Support youtube-transcript-api: dict rows (older) and FetchedTranscriptSnippet (1.2+)."""
    if isinstance(item, dict):
        return item.get('text') or ''
    text = getattr(item, 'text', None)
    return text if isinstance(text, str) else ''


def load_with_youtube_transcript_api(video_id: str) -> dict[str, Any]:
    try:
        from youtube_transcript_api import YouTubeTranscriptApi
    except ImportError as exc:
        raise RuntimeError('missing dependency: youtube-transcript-api') from exc

    api = YouTubeTranscriptApi()
    transcript_list = api.list(video_id)

    preferred_transcript = None
    preferred_source = 'unknown'

    try:
        preferred_transcript = transcript_list.find_manually_created_transcript([])
        preferred_source = 'manual'
    except Exception as exc:
        metadata_error = str(exc).strip() or 'metadata unavailable'
    else:
        metadata_error = None

    if preferred_transcript is None:
        try:
            preferred_transcript = transcript_list.find_generated_transcript([])
            preferred_source = 'autogenerated'
        except Exception:
            pass

    if preferred_transcript is None:
        for transcript in transcript_list:
            preferred_transcript = transcript
            preferred_source = 'autogenerated' if getattr(transcript, 'is_generated', False) else 'manual'
            break

    if preferred_transcript is None:
        raise RuntimeError('transcript unavailable')

    fetched = preferred_transcript.fetch()
    pieces: list[str] = []
    for item in fetched:
        text_value = transcript_line_text(item)
        cleaned_value = normalize_text(text_value)
        if cleaned_value:
            pieces.append(cleaned_value)

    transcript_text = '\n'.join(pieces).strip()
    if not transcript_text:
        raise RuntimeError('transcript unavailable')

    return {
        'transcript': transcript_text,
        'transcript_language': getattr(preferred_transcript, 'language', None),
        'transcript_language_code': getattr(preferred_transcript, 'language_code', None),
        'transcript_source': preferred_source,
        'retrieval_method': 'youtube-transcript-api',
    }


def load_with_ytdlp(video_url: str) -> dict[str, Any]:
    try:
        import yt_dlp
    except ImportError as exc:
        raise RuntimeError('missing dependency: yt-dlp') from exc

    options = {
        'skip_download': True,
        'quiet': True,
        'no_warnings': True,
        'writesubtitles': False,
        'writeautomaticsub': False,
    }

    with yt_dlp.YoutubeDL(options) as downloader:
        info = downloader.extract_info(video_url, download=False)

    result: dict[str, Any] = {
        'title': info.get('title'),
        'publish_date': info.get('upload_date'),
        'duration_seconds': info.get('duration'),
        'duration_human': format_duration(info.get('duration')),
        'canonical_url': info.get('webpage_url') or video_url,
        'video_id': info.get('id'),
    }

    subtitles = info.get('subtitles') or {}
    automatic_captions = info.get('automatic_captions') or {}

    def pick_caption_source() -> tuple[str | None, str | None, list[dict[str, Any]] | None]:
        if subtitles:
            language_code = next(iter(subtitles.keys()))
            return 'manual', language_code, subtitles.get(language_code)
        if automatic_captions:
            language_code = next(iter(automatic_captions.keys()))
            return 'autogenerated', language_code, automatic_captions.get(language_code)
        return None, None, None

    transcript_source, language_code, caption_entries = pick_caption_source()
    if caption_entries:
        caption_url = None
        for entry in caption_entries:
            if entry.get('url'):
                caption_url = entry['url']
                break
        if caption_url:
            with urllib.request.urlopen(caption_url, timeout=20) as response:
                body = response.read().decode('utf-8', errors='replace')
            transcript_text = extract_text_from_caption_payload(body)
            if transcript_text:
                result.update({
                    'transcript': transcript_text,
                    'transcript_language_code': language_code,
                    'transcript_language': language_code,
                    'transcript_source': transcript_source,
                    'retrieval_method': 'yt-dlp-captions',
                })
    return result


def extract_text_from_caption_payload(payload: str) -> str | None:
    text_fragments: list[str] = []

    xml_matches = re.findall(r'<text[^>]*>(.*?)</text>', payload, flags=re.DOTALL)
    if xml_matches:
        for match in xml_matches:
            cleaned_value = normalize_text(re.sub(r'<[^>]+>', ' ', match))
            if cleaned_value:
                text_fragments.append(cleaned_value)

    if not text_fragments:
        json_text_matches = re.findall(r'"utf8"\s*:\s*"(.*?)"', payload)
        for match in json_text_matches:
            cleaned_value = normalize_text(match.encode('utf-8').decode('unicode_escape', errors='ignore'))
            if cleaned_value:
                text_fragments.append(cleaned_value)

    if not text_fragments:
        return None

    return '\n'.join(text_fragments).strip()


def compact_publish_date(value: str | None) -> str | None:
    if not value:
        return None
    if re.fullmatch(r'\d{8}', value):
        return f'{value[:4]}-{value[4:6]}-{value[6:8]}'
    iso = re.match(r'(\d{4}-\d{2}-\d{2})', value.strip())
    if iso:
        return iso.group(1)
    return value


def extract_yt_initial_player_response(html: str) -> dict[str, Any] | None:
    for marker in ('ytInitialPlayerResponse = ', 'ytInitialPlayerResponse='):
        pos = html.find(marker)
        if pos == -1:
            continue
        brace = html.find('{', pos + len(marker))
        if brace == -1:
            continue
        try:
            data, _ = json.JSONDecoder().raw_decode(html, brace)
        except json.JSONDecodeError:
            continue
        if isinstance(data, dict):
            return data
    return None


def load_watch_html_metadata(video_id: str) -> dict[str, Any]:
    watch_url = f'https://www.youtube.com/watch?v={video_id}'
    req = urllib.request.Request(
        watch_url,
        headers={
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            'Accept-Language': 'en-US,en;q=0.9',
        },
    )
    with urllib.request.urlopen(req, timeout=25) as response:
        html = response.read().decode('utf-8', errors='replace')
    player = extract_yt_initial_player_response(html)
    if not player:
        raise RuntimeError('ytInitialPlayerResponse not found')
    details = player.get('videoDetails') or {}
    micro = (player.get('microformat') or {}).get('playerMicroformatRenderer') or {}
    raw_length = details.get('lengthSeconds')
    duration_seconds: int | None = None
    if raw_length is not None:
        try:
            duration_seconds = int(raw_length)
        except (TypeError, ValueError):
            duration_seconds = None
    publish_raw = micro.get('publishDate') or micro.get('uploadDate')
    return {
        'title': details.get('title'),
        'publish_date': publish_raw,
        'duration_seconds': duration_seconds,
        'duration_human': format_duration(duration_seconds),
    }


def merge_watch_html_metadata(
    result: TranscriptResult,
    video_id: str,
    attempted_methods: list[str],
) -> None:
    if result.title is not None and result.publish_date is not None and result.duration_seconds is not None:
        return
    if 'watch-html-player-response' not in attempted_methods:
        attempted_methods.append('watch-html-player-response')
    try:
        extra = load_watch_html_metadata(video_id)
    except Exception:
        return
    if result.title is None and extra.get('title'):
        result.title = extra['title']
    if result.publish_date is None and extra.get('publish_date'):
        result.publish_date = compact_publish_date(extra['publish_date'])
    if result.duration_seconds is None and extra.get('duration_seconds') is not None:
        result.duration_seconds = extra['duration_seconds']
        result.duration_human = extra.get('duration_human') or format_duration(extra['duration_seconds'])


def process_url(video_url: str) -> TranscriptResult:
    attempted_methods: list[str] = []
    video_id, canonical_url = parse_video_id(video_url)
    result = TranscriptResult(input_url=video_url, canonical_url=canonical_url, video_id=video_id, attempted_methods=attempted_methods)

    if not video_id:
        result.failure_reason = 'invalid youtube url'
        return result

    metadata: dict[str, Any] = {}
    metadata_error: str | None = None
    try:
        attempted_methods.append('yt-dlp-metadata')
        metadata = load_with_ytdlp(canonical_url or video_url)
        result.title = metadata.get('title')
        result.publish_date = compact_publish_date(metadata.get('publish_date'))
        result.duration_seconds = metadata.get('duration_seconds')
        result.duration_human = metadata.get('duration_human')
        result.canonical_url = metadata.get('canonical_url') or result.canonical_url
        result.video_id = metadata.get('video_id') or result.video_id
    except Exception as exc:
        metadata_error = str(exc).strip() or 'metadata unavailable'

    merge_watch_html_metadata(result, video_id, attempted_methods)

    try:
        attempted_methods.append('youtube-transcript-api')
        transcript_data = load_with_youtube_transcript_api(video_id)
        result.transcript = transcript_data.get('transcript')
        result.transcript_language = transcript_data.get('transcript_language')
        result.transcript_language_code = transcript_data.get('transcript_language_code')
        result.transcript_source = transcript_data.get('transcript_source')
        result.retrieval_method = transcript_data.get('retrieval_method')
        return result
    except Exception as exc:
        transcript_error = str(exc).strip() or 'transcript unavailable'
    
    if metadata.get('transcript'):
        result.transcript = metadata.get('transcript')
        result.transcript_language = metadata.get('transcript_language')
        result.transcript_language_code = metadata.get('transcript_language_code')
        result.transcript_source = metadata.get('transcript_source')
        result.retrieval_method = metadata.get('retrieval_method')
        return result

    attempted_methods.append('page-metadata-fallback')
    if result.title or result.publish_date or result.duration_human:
        result.failure_reason = transcript_error
    elif transcript_error.startswith('missing dependency') and metadata_error:
        result.failure_reason = f'{transcript_error}; {metadata_error}'
    elif transcript_error.startswith('missing dependency'):
        result.failure_reason = transcript_error
    elif metadata_error:
        result.failure_reason = f'{transcript_error}; {metadata_error}'
    else:
        result.failure_reason = 'video unavailable or transcript unavailable'
    return result


def main(argv: list[str]) -> int:
    if hasattr(sys.stdout, 'reconfigure'):
        try:
            sys.stdout.reconfigure(encoding='utf-8', errors='replace')
        except Exception:
            pass

    if len(argv) < 2:
        print(json.dumps({'error': 'usage: fetch_youtube_transcript.py <url1> <url2> ...'}))
        return 1

    results = [asdict(process_url(url)) for url in argv[1:]]
    print(json.dumps({'videos': results}, ensure_ascii=False, indent=2))
    return 0


if __name__ == '__main__':
    raise SystemExit(main(sys.argv))
